services:
  backend:
    image: ${LOCAL_IMG_TAG}
    ports:
      - "8080:8080"
    environment:
      - PREDICTIONS_STREAM_NAME=${PREDICTIONS_STREAM_NAME}
      - RUN_ID=3cbf46c116d7466c8934f1ca53e34cd5
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-2
      - S3_ENDPOINT_URL=http://localhost:4566
    network_mode: host
