[tool.pylint.'MESSAGES CONTROL']
disable = [
    "missing-function-docstring",
    "missing-class-docstring",
    "too-few-public-methods",
    "missing-module-docstring",
    "too-many-arguments",
    "invalid-name"
]

[tool.black]
line-length = 90
target-version = ['py39']
skip-string-normalization = true

[tool.isort]
multi_line_output = 3
length_sort = true
