# Use the specified base image
FROM agrigorev/zoomcamp-model:mlops-2024-3.10.13-slim

# Set the working directory to /app
WORKDIR /app

# Install pipenv
RUN pip install pipenv

# Copy the Pipfile and Pipfile.lock into the current working directory
COPY Pipfile Pipfile.lock .

# Install the dependencies using pipenv
RUN pipenv install --deploy --system

# Copy your script into the current working directory
COPY script.py .

# Set the entry point to your script
ENTRYPOINT ["python", "script.py"]