[tool.pylint.'MESSAGES CONTROL']
disable = [
    "missing-function-docstring",
    "invalid-name",
    "pointless-statement",
    "unexpected-keyword-arg",
    "undefined-variable",
    "line-too-long",
    "missing-module-docstring",
    "no-else-return",
    "import-error",
    "wrong-import-position",
]